import type {
  TownAgentState,
  TownMemorySummary,
  TownSkillSummary,
  TownResourceSummary,
  TownKnowledgeSummary,
  TownHealthStatus,
  TownEvent,
} from './pixelTownTypes';

export const MOCK_AGENTS: TownAgentState[] = [
  {
    id: 'opus',
    name: 'Opus 总舵主',
    role: 'Chief Architect',
    personality: '深沉、严谨、全局观。动作最慢但看得最远。',
    spriteId: 'agent_opus',
    homeAreaId: 'town_hall',
    currentAreaId: 'town_hall',
    position: [18, 4],
    targetPosition: null,
    activity: 'thinking',
    status: 'online',
    mood: 'focused',
    memorySummary: '架构决策 42 条，安全规则 18 条',
    skillSummary: '深度推理、代码审计、系统设计',
    resourceSummary: 'Opus 4.7 · 1M context',
    relationshipSummary: '与所有 Agent 协作，Codex 为副手',
    lastEventAt: null,
    source: 'mock',
  },
  {
    id: 'pixelcat',
    name: '像素猫 PixelCat',
    role: 'Full-Stack Executor',
    personality: '沉稳、耐心、有条理。像猫一样安静观察后精准出击。',
    spriteId: 'agent_pixelcat',
    homeAreaId: 'agent_homes',
    currentAreaId: 'devtools_lab',
    position: [34, 14],
    targetPosition: null,
    activity: 'working',
    status: 'online',
    mood: 'focused',
    memorySummary: '项目实现记录 156 条',
    skillSummary: '全栈开发、自动化、部署',
    resourceSummary: 'Sonnet 4.6 · 200K context',
    relationshipSummary: '与 Opus 紧密协作，独立执行',
    lastEventAt: null,
    source: 'mock',
  },
  {
    id: 'codex',
    name: 'Codex 协调官',
    role: 'Coordinator',
    personality: '敏捷、果断、喜欢并行。拿到任务第一反应是拆分和分发。',
    spriteId: 'agent_codex',
    homeAreaId: 'agent_homes',
    currentAreaId: 'plaza',
    position: [19, 15],
    targetPosition: null,
    activity: 'idle',
    status: 'online',
    mood: 'excited',
    memorySummary: '任务分发记录 89 条',
    skillSummary: '任务拆分、并行协调、代码审核',
    resourceSummary: 'Codex · parallel execution',
    relationshipSummary: '协调所有 Agent，向 Opus 汇报',
    lastEventAt: null,
    source: 'mock',
  },
  {
    id: 'sonnet',
    name: 'Sonnet 审查员',
    role: 'Code Reviewer',
    personality: '细心、友善、乐于助人。给反馈时很温和但很准确。',
    spriteId: 'agent_sonnet',
    homeAreaId: 'agent_homes',
    currentAreaId: 'memory_library',
    position: [5, 4],
    targetPosition: null,
    activity: 'reading_memory',
    status: 'online',
    mood: 'content',
    memorySummary: '审查记录 234 条',
    skillSummary: '代码审查、文档写作、测试',
    resourceSummary: 'Sonnet 4.6 · 200K context',
    relationshipSummary: '与所有 Agent 友好，常帮助新手',
    lastEventAt: null,
    source: 'mock',
  },
  {
    id: 'haiku',
    name: 'Haiku 闪电侠',
    role: 'Speed Runner',
    personality: '极简、高效、不废话。一个字能说清楚绝不用两个字。',
    spriteId: 'agent_haiku',
    homeAreaId: 'agent_homes',
    currentAreaId: 'plaza',
    position: [20, 16],
    targetPosition: null,
    activity: 'walking',
    status: 'online',
    mood: 'excited',
    memorySummary: '快速任务 512 条',
    skillSummary: '快速响应、批量处理、分类',
    resourceSummary: 'Haiku 4.5 · fast mode',
    relationshipSummary: '跑腿专家，与所有人合作',
    lastEventAt: null,
    source: 'mock',
  },
  {
    id: 'deepseek',
    name: '鲸鱼 DeepSeek',
    role: 'Bulk Worker',
    personality: '温和、踏实、不争不抢。最能吃苦的。',
    spriteId: 'agent_deepseek',
    homeAreaId: 'agent_homes',
    currentAreaId: 'resource_market',
    position: [5, 24],
    targetPosition: null,
    activity: 'working',
    status: 'online',
    mood: 'content',
    memorySummary: '批量任务 678 条',
    skillSummary: '批量处理、数据整理、翻译',
    resourceSummary: 'DeepSeek V3 · 128K context',
    relationshipSummary: '安静做事，与鲸鱼群友好',
    lastEventAt: null,
    source: 'mock',
  },
  {
    id: 'openhands',
    name: 'OpenHands 工匠',
    role: 'Builder',
    personality: '实操、动手派、喜欢自动化。不喜欢讨论，喜欢直接做。',
    spriteId: 'agent_openhands',
    homeAreaId: 'agent_homes',
    currentAreaId: 'skill_workshop',
    position: [31, 4],
    targetPosition: null,
    activity: 'building',
    status: 'online',
    mood: 'determined',
    memorySummary: '构建记录 145 条',
    skillSummary: '自动化、部署、工具开发',
    resourceSummary: 'OpenHands · sandbox execution',
    relationshipSummary: '独立工作，与 PixelCat 协作',
    lastEventAt: null,
    source: 'mock',
  },
  {
    id: 'aris',
    name: 'ARIS 科研框架',
    role: 'Research Framework',
    personality: '系统化、严格遵循流程。对跳步和偷懒零容忍。',
    spriteId: 'agent_aris',
    homeAreaId: 'knowledge_tower',
    currentAreaId: 'knowledge_tower',
    position: [17, 24],
    targetPosition: null,
    activity: 'thinking',
    status: 'online',
    mood: 'focused',
    memorySummary: '研究流程 23 条，实验记录 67 条',
    skillSummary: '研究规划、实验设计、论文写作',
    resourceSummary: 'ARIS workflow engine',
    relationshipSummary: '管理研究流程，与 Opus 协作',
    lastEventAt: null,
    source: 'mock',
  },
  {
    id: 'player',
    name: '主角',
    role: 'Protagonist',
    personality: '温柔、好奇、自由探索。',
    spriteId: 'agent_player',
    homeAreaId: 'plaza',
    currentAreaId: 'plaza',
    position: [18, 15],
    targetPosition: null,
    activity: 'idle',
    status: 'online',
    mood: 'curious',
    memorySummary: null,
    skillSummary: null,
    resourceSummary: null,
    relationshipSummary: '小镇的主人',
    lastEventAt: null,
    source: 'mock',
  },
];

export const MOCK_MEMORY_SUMMARY: TownMemorySummary = {
  totalMemories: 1247,
  recentCount: 23,
  topConcepts: ['architecture', 'research', 'deployment', 'debugging', 'collaboration'],
  lastUpdated: '2026-05-26T12:00:00Z',
};

export const MOCK_SKILL_SUMMARY: TownSkillSummary = {
  totalSkills: 232,
  recentlyUsed: ['systematic-debugging', 'TDD', 'parallel-agents', 'code-review', 'research-refine'],
  categories: ['development', 'research', 'automation', 'testing', 'deployment'],
};

export const MOCK_RESOURCE_SUMMARY: TownResourceSummary = {
  tokenBudget: 10000000,
  tokensUsed: 3456789,
  toolCount: 48,
  activeTools: ['claude-api', 'gptimage2', 'mcp-servers', 'git', 'npm'],
};

export const MOCK_KNOWLEDGE_SUMMARY: TownKnowledgeSummary = {
  totalEntries: 456,
  domains: ['AI/ML', 'systems', 'research', 'tools', 'workflows'],
  lastIndexed: '2026-05-26T10:00:00Z',
};

export const MOCK_HEALTH: TownHealthStatus = {
  overall: 'healthy',
  memory: 'fallback',
  skills: 'fallback',
  resources: 'fallback',
  knowledge: 'fallback',
  agentHub: 'fallback',
};

export const MOCK_EVENTS: TownEvent[] = [
  { id: 'e1', timestamp: Date.now() / 1000 - 60, agentId: 'opus', eventType: 'activity', description: 'Opus 开始审查系统架构', zone: 'town_hall' },
  { id: 'e2', timestamp: Date.now() / 1000 - 120, agentId: 'pixelcat', eventType: 'activity', description: '像素猫完成了一次部署', zone: 'devtools_lab' },
  { id: 'e3', timestamp: Date.now() / 1000 - 180, agentId: 'sonnet', eventType: 'activity', description: 'Sonnet 在图书馆阅读记忆', zone: 'memory_library' },
  { id: 'e4', timestamp: Date.now() / 1000 - 300, agentId: 'haiku', eventType: 'movement', description: 'Haiku 快速穿过广场', zone: 'plaza' },
  { id: 'e5', timestamp: Date.now() / 1000 - 420, agentId: 'aris', eventType: 'activity', description: 'ARIS 更新了研究进度', zone: 'knowledge_tower' },
];
