import type { TownAreaEntity } from './pixelTownTypes';

export const TOWN_AREAS: TownAreaEntity[] = [
  {
    id: 'town_hall',
    name: 'Town Hall',
    nameCn: '镇政厅',
    type: 'building',
    position: { x: 14, y: 2 },
    size: { w: 8, h: 5 },
    visualAnchor: '/assets/town/buildings/building_town_hall.png',
    description: '小镇的决策中心。Opus 在这里做架构设计和全局决策。',
    icon: '🏛️',
    adapterSource: 'townAgentAdapter',
    fallbackState: 'mock',
    systemLink: 'agent-hub',
  },
  {
    id: 'memory_library',
    name: 'Memory Library',
    nameCn: '记忆图书馆',
    type: 'building',
    position: { x: 2, y: 2 },
    size: { w: 7, h: 5 },
    visualAnchor: '/assets/town/buildings/building_memory_library.png',
    description: '存放所有 Agent 的长期记忆。连接 AgentMemory 和共享 Memory 系统。',
    icon: '📚',
    adapterSource: 'townMemoryAdapter',
    fallbackState: 'mock',
    systemLink: 'agentmemory',
  },
  {
    id: 'skill_workshop',
    name: 'Skill Workshop',
    nameCn: '技能工坊',
    type: 'building',
    position: { x: 28, y: 2 },
    size: { w: 7, h: 5 },
    visualAnchor: '/assets/town/buildings/building_skill_workshop.png',
    description: '232+ 技能的训练和使用场所。OpenHands 最爱来这里。',
    icon: '🔧',
    adapterSource: 'townSkillAdapter',
    fallbackState: 'mock',
    systemLink: 'skills',
  },
  {
    id: 'dream_garden',
    name: 'Dream Garden',
    nameCn: '梦境花园',
    type: 'building',
    position: { x: 2, y: 12 },
    size: { w: 7, h: 5 },
    visualAnchor: '/assets/town/buildings/building_dream_garden.png',
    description: 'Agent 休息和灵感涌现的地方。代表夜间思考和记忆沉淀。',
    icon: '🌸',
    adapterSource: 'townEventAdapter',
    fallbackState: 'mock',
    systemLink: null,
  },
  {
    id: 'plaza',
    name: 'Central Plaza',
    nameCn: '中央广场',
    type: 'landmark',
    position: { x: 14, y: 11 },
    size: { w: 12, h: 8 },
    visualAnchor: '/assets/town/buildings/building_plaza.png',
    description: '小镇的心脏。Agent 们在这里相遇、交流、分享信息。',
    icon: '⛲',
    adapterSource: 'townHealthAdapter',
    fallbackState: 'mock',
    systemLink: null,
  },
  {
    id: 'devtools_lab',
    name: 'Devtools Lab',
    nameCn: '开发实验室',
    type: 'building',
    position: { x: 32, y: 12 },
    size: { w: 6, h: 5 },
    visualAnchor: '/assets/town/buildings/building_devtools_lab.png',
    description: '所有开发工具和基础设施的实验室。像素猫的主场。',
    icon: '🔬',
    adapterSource: 'townResourceAdapter',
    fallbackState: 'mock',
    systemLink: 'devtools',
  },
  {
    id: 'resource_market',
    name: 'Resource Market',
    nameCn: '资源市场',
    type: 'building',
    position: { x: 2, y: 22 },
    size: { w: 7, h: 5 },
    visualAnchor: '/assets/town/buildings/building_resource_market.png',
    description: 'API 调用、token 消耗、计算资源的交易和监控中心。',
    icon: '🏪',
    adapterSource: 'townResourceAdapter',
    fallbackState: 'mock',
    systemLink: 'agent-resources',
  },
  {
    id: 'knowledge_tower',
    name: 'Knowledge Tower',
    nameCn: '知识塔',
    type: 'building',
    position: { x: 15, y: 22 },
    size: { w: 5, h: 5 },
    visualAnchor: '/assets/town/buildings/building_knowledge_tower.png',
    description: 'Vipin Knowledgebase 的实体化。ARIS 在这里管理研究流程。',
    icon: '🗼',
    adapterSource: 'townKnowledgeAdapter',
    fallbackState: 'mock',
    systemLink: 'vipinknowledge',
  },
  {
    id: 'agent_homes',
    name: 'Agent Homes',
    nameCn: '居民住宅',
    type: 'building',
    position: { x: 30, y: 22 },
    size: { w: 8, h: 5 },
    visualAnchor: '/assets/town/buildings/building_agent_homes.png',
    description: 'Agent 们的家。每个 Agent 都有自己的小房间。',
    icon: '🏠',
    adapterSource: 'townAgentAdapter',
    fallbackState: 'mock',
    systemLink: null,
  },
];

export function getAreaById(id: string): TownAreaEntity | undefined {
  return TOWN_AREAS.find(a => a.id === id);
}

export function getAreaAtTile(tx: number, ty: number): TownAreaEntity | undefined {
  return TOWN_AREAS.find(a =>
    tx >= a.position.x && tx < a.position.x + a.size.w &&
    ty >= a.position.y && ty < a.position.y + a.size.h
  );
}
